version: '3'

services:
  db:
    container_name: db_main_study
    hostname: db_main_study
    image: postgres:10.0-alpine
    volumes:
      - pg_data_main:/var/lib/postresql/data/pg_data
    restart: always
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_DB: locations
      POSTGRES_USER: app
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pg_data
    ports:
      - "54320:5432"

volumes:
  pg_data_main:
