version: '3'

services:
  db:
    container_name: db_main
    hostname: db_main
    image: postgres:10.0-alpine
    networks:
      - net
    volumes:
      - pg_data_main:/var/lib/postresql/data/pg_data
    restart: always
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_DB: locations
      POSTGRES_USER: app
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pg_data
    ports:
      - "54320:5432"
networks:
  net:

volumes:
  pg_data_main:
